version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "less"
      - dependency-name: "less-loader"
      - dependency-name: "bizcharts"
