mutation login($data: InputLogin!) {
    login(data: $data) {
        id
        name
        createdAt
        token
    }
}

query initialCheck {
    profile {
        id
        name
        createdAt
    }
}
